"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "./ui/button";
import { formatDate } from "@/lib/models";
import styles from "./employee-workspace.module.css";
type Absence = { id: number; employeeId: number; startsAt: string; endsAt: string; reason: string };
export function EmployeeAvailability({ employees }: { employees: { id: number; name: string }[] }) {
  const [items, setItems] = useState<Absence[]>([]), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [opened, setOpened] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/workspaces/availability", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.absences); } catch (failure) { setError(failure instanceof Error ? failure.message : "Ausências indisponíveis."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function mutate(body: unknown, method: string) {
    if (busy) return; setBusy(true); setError(""); setNotice("");
    try { const response = await fetch("/api/workspaces/availability", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); setOpened(false); setNotice(method === "DELETE" ? "Ausência removida." : "Ausência registrada."); } catch (failure) { setError(failure instanceof Error ? failure.message : "Não foi possível salvar."); } finally { setBusy(false); }
  }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void mutate({ employeeId: Number(form.get("employeeId")), startsAt: String(form.get("startsAt")), endsAt: String(form.get("endsAt")), reason: String(form.get("reason")) }, "POST"); }
  return <section className={styles.absences} aria-labelledby="absences-title"><div className={styles.heading}><h2 id="absences-title">Ausências da equipe</h2><Button variant="outline" disabled={busy || !employees.length} onClick={() => setOpened(value => !value)}><Plus aria-hidden="true" />Nova ausência</Button></div>{opened && <form className={styles.editor} onSubmit={submit}><div className={styles.fields}><label>Funcionário<select name="employeeId" required disabled={busy}><option value="">Selecione</option>{employees.map(employee => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label><label>Motivo (opcional)<input name="reason" maxLength={120} disabled={busy} /></label><label>Início · Brasília<input type="datetime-local" step={60} name="startsAt" required disabled={busy} /></label><label>Fim · Brasília<input type="datetime-local" step={60} name="endsAt" required disabled={busy} /></label></div><Button disabled={busy}>Salvar ausência</Button></form>}{error && <p role="alert" className={styles.error}>{error}</p>}{notice && <p role="status" className={styles.notice}>{notice}</p>}<ul className={styles.directory}>{items.map(item => <li key={item.id}><div className={styles.person}><h3>{employees.find(employee => employee.id === item.employeeId)?.name ?? "Funcionário arquivado"}</h3><p>{formatDate(item.startsAt)} {item.startsAt.slice(11)} a {formatDate(item.endsAt)} {item.endsAt.slice(11)}</p>{item.reason && <p>{item.reason}</p>}</div><Button variant="ghost" size="icon" aria-label="Remover ausência" title="Remover ausência" disabled={busy} onClick={() => { if (window.confirm("Remover esta ausência e liberar o período?")) void mutate({ id: item.id }, "DELETE"); }}><Trash2 aria-hidden="true" /></Button></li>)}</ul>{!items.length && !error && <p className={styles.empty}>Nenhuma ausência registrada.</p>}{items.length === 250 && <p role="status">Mostrando as primeiras 250 ausências.</p>}</section>;
}
