"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Check, RefreshCw } from "lucide-react";
import { Button } from "./ui/button";
import type { OperationTask } from "@/lib/operations-queue";
type Queue = { tasks: OperationTask[]; total: number; truncated: boolean; firstRun: boolean; hasCustomer: boolean };
export function OperationsQueue({ revision }: { revision: number }) {
  const [queue, setQueue] = useState<Queue | null>(null), [error, setError] = useState(""), [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); setError(""); void fetch("/api/operations/queue", { cache: "no-store", signal: controller.signal }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); if (!controller.signal.aborted) setQueue(data); }).catch(failure => { if (!controller.signal.aborted) setError(failure.message); }); return () => controller.abort(); }, [revision, retry]);
  return <section className="mt-5 border-y border-[#ebe9e4] py-5" aria-labelledby="operations-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="operations-title" className="text-lg font-semibold">{queue?.firstRun ? "Seu primeiro atendimento" : "Próximas ações"}</h2><Button variant="ghost" size="icon" title="Atualizar próximas ações" aria-label="Atualizar próximas ações" onClick={() => setRetry(value => value + 1)}><RefreshCw aria-hidden="true" /></Button></div>{error ? <p role="alert" className="mt-3 text-sm text-red-700">{error}</p> : !queue ? <p role="status" className="mt-3 text-sm text-[#6f6d68]">Organizando pendências...</p> : queue.firstRun ? <ol className="mt-3 grid gap-3 sm:grid-cols-3">{[{ label: "Cadastrar cliente", href: "/clientes?novo=1", done: queue.hasCustomer }, { label: "Criar orçamento", href: "/novo-orcamento", done: false }, { label: "Agendar atendimento", href: "/agenda", done: false }].map((task, index) => <li key={task.href} className="flex items-center gap-3 border-b border-[#ebe9e4] py-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-md bg-[#eef3ff] font-semibold text-[#2350d8]">{task.done ? <Check aria-label="Concluído" className="size-4" /> : index + 1}</span><Link href={task.href} className="break-words text-sm font-semibold text-[#2350d8] underline-offset-4 hover:underline">{task.label}</Link></li>)}</ol> : <>{!queue.tasks.length ? <p className="mt-3 text-sm text-[#6f6d68]">Nenhuma ação operacional pendente nos registros consultados.</p> : <ul className="mt-2 divide-y divide-[#ebe9e4]">{queue.tasks.map(task => <li key={task.key} className="flex min-w-0 flex-col justify-between gap-3 py-3 sm:flex-row sm:items-center"><div className="min-w-0"><h3 className="break-words text-base font-semibold">{task.label}</h3><p className="mt-1 break-words text-sm text-[#6f6d68]">{task.detail}</p></div><Button asChild variant="outline" className="w-fit max-w-full shrink-0"><Link href={task.href}>{task.action}</Link></Button></li>)}</ul>}{queue.total > 8 && <p className="mt-2 text-sm text-[#6f6d68]">8 de {queue.total} ações. As mais urgentes aparecem primeiro.</p>}{queue.truncated && <p role="status" className="mt-2 text-sm text-[#6f6d68]">Consulta limitada. Confira também a agenda e os orçamentos.</p>}</>}</section>;
}
