"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { CalendarPlus, CircleDollarSign } from "lucide-react";
import { Button } from "./ui/button";
import { ServiceReportButton } from "./service-report";
import { useCurrentUser } from "@/hooks/use-current-user";
import { brasiliaDay } from "@/lib/appointments";
import { formatDate, formatMoney, type Quote } from "@/lib/models";
type Workflow = { appointments: { id: number; title: string; startsAt: string; status: string }[]; charges: { id: number; status: string; dueDate: string; amountCents: number }[] };
export function QuoteWorkflow({ quote }: { quote: Quote }) {
  const { workspace } = useCurrentUser(), readonly = workspace?.role === "viewer";
  const [state, setState] = useState<Workflow | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [opened, setOpened] = useState(false), [confirmed, setConfirmed] = useState(false), [dueDate, setDueDate] = useState(brasiliaDay);
  const load = useCallback(async () => { try { const response = await fetch(`/api/quotes/${quote.id}/workflow`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setState(data); setError(""); } catch (failure) { setError(failure instanceof Error ? failure.message : "Acompanhamento indisponível."); } }, [quote.id]);
  useEffect(() => { void load(); }, [load, quote.updatedAt, quote.status]);
  if (!["Aprovado", "Em andamento", "Finalizado", "Pago"].includes(quote.status)) return null;
  async function createCharge() {
    if (busy || !confirmed) return; setBusy(true); setError("");
    try { const response = await fetch(`/api/quotes/${quote.id}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dueDate, expectedUpdatedAt: quote.updatedAt }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setOpened(false); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Não foi possível criar a cobrança."); } finally { setBusy(false); }
  }
  return <section className="print-hidden space-y-4 border-y border-[#dbe6f0] py-5" aria-labelledby="quote-workflow-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="quote-workflow-title" className="text-lg font-semibold">Do serviço ao recebimento</h2>{!readonly && <Button asChild variant="outline"><Link href={`/agenda?orcamento=${quote.id}&cliente=${quote.customerId}`}><CalendarPlus aria-hidden="true" />Agendar serviço</Link></Button>}</div>{error ? <p role="alert">{error}<Button variant="outline" className="ml-2" onClick={() => void load()}>Atualizar</Button></p> : !state ? <p role="status">Carregando acompanhamento...</p> : <><ul className="divide-y divide-[#dbe6f0]">{state.appointments.map(appointment => <li key={appointment.id} className="flex min-w-0 flex-wrap items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="break-words font-medium">{appointment.title}</p><p className="mt-1 text-sm text-[#53647b]">{formatDate(appointment.startsAt)} às {appointment.startsAt.slice(11)} · {appointment.status}</p></div><ServiceReportButton id={appointment.id} title={appointment.title} /></li>)}</ul>{!state.appointments.length && <p className="text-sm text-[#53647b]">Nenhum atendimento vinculado.</p>}{state.charges.length ? <div className="space-y-2">{state.charges.map(charge => <p key={charge.id} className="break-words text-sm">Cobrança #{charge.id} · {formatMoney(charge.amountCents)} · vence {formatDate(charge.dueDate)} · {charge.status === "paid" ? "Recebida" : charge.status === "canceled" ? "Cancelada" : "Em aberto"}</p>)}<Link href="/financas#contas-previstas" className="inline-block py-2 text-sm font-medium text-[#1454b3] underline">Abrir contas previstas</Link></div> : !readonly && quote.status !== "Pago" && <Button variant="outline" onClick={() => { setOpened(value => !value); setConfirmed(false); }}><CircleDollarSign aria-hidden="true" />Criar cobrança prevista</Button>}</>}{opened && <form className="space-y-3 border-t border-[#dbe6f0] pt-4" onSubmit={event => { event.preventDefault(); void createCharge(); }}><p className="font-semibold">{formatMoney(quote.totalCents)}</p><label className="grid max-w-xs gap-2 text-sm">Vencimento<input type="date" min="2000-01-01" max="2099-12-31" className="min-h-11 min-w-0 rounded-md border border-[#7e8ea3] bg-white px-3 text-base" required disabled={busy} value={dueDate} onChange={event => { setDueDate(event.target.value); setConfirmed(false); }} /></label><label className="flex min-h-11 items-start gap-3 text-sm leading-6"><input type="checkbox" className="mt-1 size-5 shrink-0" required disabled={busy} checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /><span>Confirmo que este valor ainda não foi recebido e não existe outra cobrança deste serviço.</span></label><Button disabled={busy || !confirmed}>Confirmar cobrança</Button></form>}</section>;
}
