-- Vemo: diagnóstico completo do banco. SOMENTE LEITURA: não cria, altera nem apaga nada.
-- Selecione o banco do Vemo no phpMyAdmin, cole tudo na aba SQL e clique em Executar.
-- Mande um print (ou exporte) do resultado. Mostra só o que falta, mais duas linhas de informação.

SELECT * FROM (
  SELECT '1-INFO' AS tipo, 'versao do banco' AS tabela, VERSION() AS detalhe
  UNION ALL
  SELECT '1-INFO', 'users.id', CONCAT(c.COLUMN_TYPE, ' / motor ', t.ENGINE, ' / ', t.TABLE_COLLATION)
  FROM information_schema.COLUMNS c JOIN information_schema.TABLES t ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
  WHERE c.TABLE_SCHEMA = DATABASE() AND c.TABLE_NAME = 'users' AND c.COLUMN_NAME = 'id'
  UNION ALL
  SELECT '2-FALTA_TABELA', e.t, '' FROM (SELECT DISTINCT t FROM (
    SELECT 'account_tokens' AS t, 'id' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'user_id' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'purpose' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'email' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'expires_at' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'created_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'id' AS c
    UNION ALL SELECT 'appointments' AS t, 'user_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'customer_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'service_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'employee_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'quote_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'series_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'occurrence_key' AS c
    UNION ALL SELECT 'appointments' AS t, 'customer_name' AS c
    UNION ALL SELECT 'appointments' AS t, 'title' AS c
    UNION ALL SELECT 'appointments' AS t, 'starts_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'ends_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'duration_minutes' AS c
    UNION ALL SELECT 'appointments' AS t, 'notes' AS c
    UNION ALL SELECT 'appointments' AS t, 'status' AS c
    UNION ALL SELECT 'appointments' AS t, 'version' AS c
    UNION ALL SELECT 'appointments' AS t, 'request_key' AS c
    UNION ALL SELECT 'appointments' AS t, 'created_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'updated_at' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'id' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'user_id' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'recurrence' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'interval_count' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'starts_on' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'ends_on' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'created_at' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'user_id' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'usage_day' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'request_count' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'updated_at' AS c
    UNION ALL SELECT 'billing_events' AS t, 'id' AS c
    UNION ALL SELECT 'billing_events' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'billing_events' AS t, 'type' AS c
    UNION ALL SELECT 'billing_events' AS t, 'created_at' AS c
    UNION ALL SELECT 'business_activity' AS t, 'id' AS c
    UNION ALL SELECT 'business_activity' AS t, 'user_id' AS c
    UNION ALL SELECT 'business_activity' AS t, 'action' AS c
    UNION ALL SELECT 'business_activity' AS t, 'entity_type' AS c
    UNION ALL SELECT 'business_activity' AS t, 'entity_id' AS c
    UNION ALL SELECT 'business_activity' AS t, 'title' AS c
    UNION ALL SELECT 'business_activity' AS t, 'details' AS c
    UNION ALL SELECT 'business_activity' AS t, 'reversible' AS c
    UNION ALL SELECT 'business_activity' AS t, 'undone_at' AS c
    UNION ALL SELECT 'business_activity' AS t, 'created_at' AS c
    UNION ALL SELECT 'business_logos' AS t, 'user_id' AS c
    UNION ALL SELECT 'business_logos' AS t, 'data_url' AS c
    UNION ALL SELECT 'business_logos' AS t, 'updated_at' AS c
    UNION ALL SELECT 'customers' AS t, 'id' AS c
    UNION ALL SELECT 'customers' AS t, 'user_id' AS c
    UNION ALL SELECT 'customers' AS t, 'name' AS c
    UNION ALL SELECT 'customers' AS t, 'phone' AS c
    UNION ALL SELECT 'customers' AS t, 'email' AS c
    UNION ALL SELECT 'customers' AS t, 'address' AS c
    UNION ALL SELECT 'customers' AS t, 'notes' AS c
    UNION ALL SELECT 'customers' AS t, 'created_at' AS c
    UNION ALL SELECT 'customers' AS t, 'request_key' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'id' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'employee_id' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'starts_at' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'ends_at' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'reason' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'created_at' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'appointment_id' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'employee_id' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'instructions' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'assigned_by' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'updated_at' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'user_id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'quote_id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'customer_id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'type' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'description' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'amount_cents' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'due_date' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'status' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'installment_group' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'installment_number' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'installment_count' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'request_key' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'version' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'created_at' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'updated_at' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'id' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'attempts' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'window_started_at' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'blocked_until' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'updated_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'id' AS c
    UNION ALL SELECT 'quotes' AS t, 'user_id' AS c
    UNION ALL SELECT 'quotes' AS t, 'customer_id' AS c
    UNION ALL SELECT 'quotes' AS t, 'client_snapshot' AS c
    UNION ALL SELECT 'quotes' AS t, 'description' AS c
    UNION ALL SELECT 'quotes' AS t, 'status' AS c
    UNION ALL SELECT 'quotes' AS t, 'valid_until' AS c
    UNION ALL SELECT 'quotes' AS t, 'deadline' AS c
    UNION ALL SELECT 'quotes' AS t, 'payment_method' AS c
    UNION ALL SELECT 'quotes' AS t, 'discount_cents' AS c
    UNION ALL SELECT 'quotes' AS t, 'created_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'updated_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'sent_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'approved_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'archived_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'public_token' AS c
    UNION ALL SELECT 'quote_items' AS t, 'id' AS c
    UNION ALL SELECT 'quote_items' AS t, 'quote_id' AS c
    UNION ALL SELECT 'quote_items' AS t, 'kind' AS c
    UNION ALL SELECT 'quote_items' AS t, 'description' AS c
    UNION ALL SELECT 'quote_items' AS t, 'quantity' AS c
    UNION ALL SELECT 'quote_items' AS t, 'unit_price_cents' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'id' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'user_id' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'transaction_id' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'version' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'previous_date' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'corrected_date' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'reason' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'created_at' AS c
    UNION ALL SELECT 'services' AS t, 'id' AS c
    UNION ALL SELECT 'services' AS t, 'user_id' AS c
    UNION ALL SELECT 'services' AS t, 'name' AS c
    UNION ALL SELECT 'services' AS t, 'description' AS c
    UNION ALL SELECT 'services' AS t, 'price_cents' AS c
    UNION ALL SELECT 'services' AS t, 'duration_minutes' AS c
    UNION ALL SELECT 'services' AS t, 'archived' AS c
    UNION ALL SELECT 'services' AS t, 'version' AS c
    UNION ALL SELECT 'services' AS t, 'request_key' AS c
    UNION ALL SELECT 'services' AS t, 'created_at' AS c
    UNION ALL SELECT 'services' AS t, 'updated_at' AS c
    UNION ALL SELECT 'service_reports' AS t, 'appointment_id' AS c
    UNION ALL SELECT 'service_reports' AS t, 'user_id' AS c
    UNION ALL SELECT 'service_reports' AS t, 'checklist' AS c
    UNION ALL SELECT 'service_reports' AS t, 'photos' AS c
    UNION ALL SELECT 'service_reports' AS t, 'summary' AS c
    UNION ALL SELECT 'service_reports' AS t, 'acknowledged_by' AS c
    UNION ALL SELECT 'service_reports' AS t, 'acknowledged_at' AS c
    UNION ALL SELECT 'service_reports' AS t, 'next_visit_on' AS c
    UNION ALL SELECT 'service_reports' AS t, 'public_token_hash' AS c
    UNION ALL SELECT 'service_reports' AS t, 'public_expires_at' AS c
    UNION ALL SELECT 'service_reports' AS t, 'version' AS c
    UNION ALL SELECT 'service_reports' AS t, 'updated_at' AS c
    UNION ALL SELECT 'sessions' AS t, 'id' AS c
    UNION ALL SELECT 'sessions' AS t, 'user_id' AS c
    UNION ALL SELECT 'sessions' AS t, 'expires_at' AS c
    UNION ALL SELECT 'sessions' AS t, 'created_at' AS c
    UNION ALL SELECT 'transactions' AS t, 'id' AS c
    UNION ALL SELECT 'transactions' AS t, 'user_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'quote_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'obligation_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'voided_at' AS c
    UNION ALL SELECT 'transactions' AS t, 'reversal_of_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'request_key' AS c
    UNION ALL SELECT 'transactions' AS t, 'receipt_version' AS c
    UNION ALL SELECT 'transactions' AS t, 'category' AS c
    UNION ALL SELECT 'transactions' AS t, 'type' AS c
    UNION ALL SELECT 'transactions' AS t, 'description' AS c
    UNION ALL SELECT 'transactions' AS t, 'amount_cents' AS c
    UNION ALL SELECT 'transactions' AS t, 'transaction_date' AS c
    UNION ALL SELECT 'transactions' AS t, 'created_at' AS c
    UNION ALL SELECT 'users' AS t, 'id' AS c
    UNION ALL SELECT 'users' AS t, 'name' AS c
    UNION ALL SELECT 'users' AS t, 'email' AS c
    UNION ALL SELECT 'users' AS t, 'phone' AS c
    UNION ALL SELECT 'users' AS t, 'password_hash' AS c
    UNION ALL SELECT 'users' AS t, 'password_salt' AS c
    UNION ALL SELECT 'users' AS t, 'created_at' AS c
    UNION ALL SELECT 'users' AS t, 'email_verified_at' AS c
    UNION ALL SELECT 'users' AS t, 'business_profile' AS c
    UNION ALL SELECT 'workspaces' AS t, 'id' AS c
    UNION ALL SELECT 'workspaces' AS t, 'owner_user_id' AS c
    UNION ALL SELECT 'workspaces' AS t, 'kind' AS c
    UNION ALL SELECT 'workspaces' AS t, 'name' AS c
    UNION ALL SELECT 'workspaces' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'customer_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'subscription_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'checkout_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'checkout_generation' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'cancel_at_period_end' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'provider_status' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'updated_at' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'id' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'user_id' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'name' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'email' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'phone' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'job_title' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'availability' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'archived' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'version' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'updated_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'id' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'email' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'role' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'invited_by' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'expires_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'accepted_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'revoked_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'user_id' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'role' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_selections' AS t, 'session_id' AS c
    UNION ALL SELECT 'workspace_selections' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'status' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'trial_starts_at' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'trial_ends_at' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'paid_until' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'updated_at' AS c
  ) x) e
  LEFT JOIN information_schema.TABLES a ON a.TABLE_SCHEMA = DATABASE() AND a.TABLE_NAME = e.t
  WHERE a.TABLE_NAME IS NULL
  UNION ALL
  SELECT '3-FALTA_COLUNA', e.t, GROUP_CONCAT(e.c ORDER BY e.c SEPARATOR ', ') FROM (
    SELECT 'account_tokens' AS t, 'id' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'user_id' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'purpose' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'email' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'expires_at' AS c
    UNION ALL SELECT 'account_tokens' AS t, 'created_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'id' AS c
    UNION ALL SELECT 'appointments' AS t, 'user_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'customer_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'service_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'employee_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'quote_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'series_id' AS c
    UNION ALL SELECT 'appointments' AS t, 'occurrence_key' AS c
    UNION ALL SELECT 'appointments' AS t, 'customer_name' AS c
    UNION ALL SELECT 'appointments' AS t, 'title' AS c
    UNION ALL SELECT 'appointments' AS t, 'starts_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'ends_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'duration_minutes' AS c
    UNION ALL SELECT 'appointments' AS t, 'notes' AS c
    UNION ALL SELECT 'appointments' AS t, 'status' AS c
    UNION ALL SELECT 'appointments' AS t, 'version' AS c
    UNION ALL SELECT 'appointments' AS t, 'request_key' AS c
    UNION ALL SELECT 'appointments' AS t, 'created_at' AS c
    UNION ALL SELECT 'appointments' AS t, 'updated_at' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'id' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'user_id' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'recurrence' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'interval_count' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'starts_on' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'ends_on' AS c
    UNION ALL SELECT 'appointment_series' AS t, 'created_at' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'user_id' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'usage_day' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'request_count' AS c
    UNION ALL SELECT 'assistant_usage' AS t, 'updated_at' AS c
    UNION ALL SELECT 'billing_events' AS t, 'id' AS c
    UNION ALL SELECT 'billing_events' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'billing_events' AS t, 'type' AS c
    UNION ALL SELECT 'billing_events' AS t, 'created_at' AS c
    UNION ALL SELECT 'business_activity' AS t, 'id' AS c
    UNION ALL SELECT 'business_activity' AS t, 'user_id' AS c
    UNION ALL SELECT 'business_activity' AS t, 'action' AS c
    UNION ALL SELECT 'business_activity' AS t, 'entity_type' AS c
    UNION ALL SELECT 'business_activity' AS t, 'entity_id' AS c
    UNION ALL SELECT 'business_activity' AS t, 'title' AS c
    UNION ALL SELECT 'business_activity' AS t, 'details' AS c
    UNION ALL SELECT 'business_activity' AS t, 'reversible' AS c
    UNION ALL SELECT 'business_activity' AS t, 'undone_at' AS c
    UNION ALL SELECT 'business_activity' AS t, 'created_at' AS c
    UNION ALL SELECT 'business_logos' AS t, 'user_id' AS c
    UNION ALL SELECT 'business_logos' AS t, 'data_url' AS c
    UNION ALL SELECT 'business_logos' AS t, 'updated_at' AS c
    UNION ALL SELECT 'customers' AS t, 'id' AS c
    UNION ALL SELECT 'customers' AS t, 'user_id' AS c
    UNION ALL SELECT 'customers' AS t, 'name' AS c
    UNION ALL SELECT 'customers' AS t, 'phone' AS c
    UNION ALL SELECT 'customers' AS t, 'email' AS c
    UNION ALL SELECT 'customers' AS t, 'address' AS c
    UNION ALL SELECT 'customers' AS t, 'notes' AS c
    UNION ALL SELECT 'customers' AS t, 'created_at' AS c
    UNION ALL SELECT 'customers' AS t, 'request_key' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'id' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'employee_id' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'starts_at' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'ends_at' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'reason' AS c
    UNION ALL SELECT 'employee_absences' AS t, 'created_at' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'appointment_id' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'employee_id' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'instructions' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'assigned_by' AS c
    UNION ALL SELECT 'employee_assignments' AS t, 'updated_at' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'user_id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'quote_id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'customer_id' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'type' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'description' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'amount_cents' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'due_date' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'status' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'installment_group' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'installment_number' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'installment_count' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'request_key' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'version' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'created_at' AS c
    UNION ALL SELECT 'financial_obligations' AS t, 'updated_at' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'id' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'attempts' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'window_started_at' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'blocked_until' AS c
    UNION ALL SELECT 'login_attempts' AS t, 'updated_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'id' AS c
    UNION ALL SELECT 'quotes' AS t, 'user_id' AS c
    UNION ALL SELECT 'quotes' AS t, 'customer_id' AS c
    UNION ALL SELECT 'quotes' AS t, 'client_snapshot' AS c
    UNION ALL SELECT 'quotes' AS t, 'description' AS c
    UNION ALL SELECT 'quotes' AS t, 'status' AS c
    UNION ALL SELECT 'quotes' AS t, 'valid_until' AS c
    UNION ALL SELECT 'quotes' AS t, 'deadline' AS c
    UNION ALL SELECT 'quotes' AS t, 'payment_method' AS c
    UNION ALL SELECT 'quotes' AS t, 'discount_cents' AS c
    UNION ALL SELECT 'quotes' AS t, 'created_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'updated_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'sent_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'approved_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'archived_at' AS c
    UNION ALL SELECT 'quotes' AS t, 'public_token' AS c
    UNION ALL SELECT 'quote_items' AS t, 'id' AS c
    UNION ALL SELECT 'quote_items' AS t, 'quote_id' AS c
    UNION ALL SELECT 'quote_items' AS t, 'kind' AS c
    UNION ALL SELECT 'quote_items' AS t, 'description' AS c
    UNION ALL SELECT 'quote_items' AS t, 'quantity' AS c
    UNION ALL SELECT 'quote_items' AS t, 'unit_price_cents' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'id' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'user_id' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'transaction_id' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'version' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'previous_date' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'corrected_date' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'reason' AS c
    UNION ALL SELECT 'receipt_date_corrections' AS t, 'created_at' AS c
    UNION ALL SELECT 'services' AS t, 'id' AS c
    UNION ALL SELECT 'services' AS t, 'user_id' AS c
    UNION ALL SELECT 'services' AS t, 'name' AS c
    UNION ALL SELECT 'services' AS t, 'description' AS c
    UNION ALL SELECT 'services' AS t, 'price_cents' AS c
    UNION ALL SELECT 'services' AS t, 'duration_minutes' AS c
    UNION ALL SELECT 'services' AS t, 'archived' AS c
    UNION ALL SELECT 'services' AS t, 'version' AS c
    UNION ALL SELECT 'services' AS t, 'request_key' AS c
    UNION ALL SELECT 'services' AS t, 'created_at' AS c
    UNION ALL SELECT 'services' AS t, 'updated_at' AS c
    UNION ALL SELECT 'service_reports' AS t, 'appointment_id' AS c
    UNION ALL SELECT 'service_reports' AS t, 'user_id' AS c
    UNION ALL SELECT 'service_reports' AS t, 'checklist' AS c
    UNION ALL SELECT 'service_reports' AS t, 'photos' AS c
    UNION ALL SELECT 'service_reports' AS t, 'summary' AS c
    UNION ALL SELECT 'service_reports' AS t, 'acknowledged_by' AS c
    UNION ALL SELECT 'service_reports' AS t, 'acknowledged_at' AS c
    UNION ALL SELECT 'service_reports' AS t, 'next_visit_on' AS c
    UNION ALL SELECT 'service_reports' AS t, 'public_token_hash' AS c
    UNION ALL SELECT 'service_reports' AS t, 'public_expires_at' AS c
    UNION ALL SELECT 'service_reports' AS t, 'version' AS c
    UNION ALL SELECT 'service_reports' AS t, 'updated_at' AS c
    UNION ALL SELECT 'sessions' AS t, 'id' AS c
    UNION ALL SELECT 'sessions' AS t, 'user_id' AS c
    UNION ALL SELECT 'sessions' AS t, 'expires_at' AS c
    UNION ALL SELECT 'sessions' AS t, 'created_at' AS c
    UNION ALL SELECT 'transactions' AS t, 'id' AS c
    UNION ALL SELECT 'transactions' AS t, 'user_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'quote_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'obligation_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'voided_at' AS c
    UNION ALL SELECT 'transactions' AS t, 'reversal_of_id' AS c
    UNION ALL SELECT 'transactions' AS t, 'request_key' AS c
    UNION ALL SELECT 'transactions' AS t, 'receipt_version' AS c
    UNION ALL SELECT 'transactions' AS t, 'category' AS c
    UNION ALL SELECT 'transactions' AS t, 'type' AS c
    UNION ALL SELECT 'transactions' AS t, 'description' AS c
    UNION ALL SELECT 'transactions' AS t, 'amount_cents' AS c
    UNION ALL SELECT 'transactions' AS t, 'transaction_date' AS c
    UNION ALL SELECT 'transactions' AS t, 'created_at' AS c
    UNION ALL SELECT 'users' AS t, 'id' AS c
    UNION ALL SELECT 'users' AS t, 'name' AS c
    UNION ALL SELECT 'users' AS t, 'email' AS c
    UNION ALL SELECT 'users' AS t, 'phone' AS c
    UNION ALL SELECT 'users' AS t, 'password_hash' AS c
    UNION ALL SELECT 'users' AS t, 'password_salt' AS c
    UNION ALL SELECT 'users' AS t, 'created_at' AS c
    UNION ALL SELECT 'users' AS t, 'email_verified_at' AS c
    UNION ALL SELECT 'users' AS t, 'business_profile' AS c
    UNION ALL SELECT 'workspaces' AS t, 'id' AS c
    UNION ALL SELECT 'workspaces' AS t, 'owner_user_id' AS c
    UNION ALL SELECT 'workspaces' AS t, 'kind' AS c
    UNION ALL SELECT 'workspaces' AS t, 'name' AS c
    UNION ALL SELECT 'workspaces' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'customer_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'subscription_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'checkout_id' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'checkout_generation' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'cancel_at_period_end' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'provider_status' AS c
    UNION ALL SELECT 'workspace_billing' AS t, 'updated_at' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'id' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'user_id' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'name' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'email' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'phone' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'job_title' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'availability' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'archived' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'version' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_employees' AS t, 'updated_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'id' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'email' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'role' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'invited_by' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'expires_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'accepted_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'revoked_at' AS c
    UNION ALL SELECT 'workspace_invites' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'user_id' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'role' AS c
    UNION ALL SELECT 'workspace_members' AS t, 'created_at' AS c
    UNION ALL SELECT 'workspace_selections' AS t, 'session_id' AS c
    UNION ALL SELECT 'workspace_selections' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'workspace_id' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'status' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'trial_starts_at' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'trial_ends_at' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'paid_until' AS c
    UNION ALL SELECT 'workspace_subscriptions' AS t, 'updated_at' AS c
  ) e
  JOIN information_schema.TABLES a ON a.TABLE_SCHEMA = DATABASE() AND a.TABLE_NAME = e.t
  LEFT JOIN information_schema.COLUMNS col ON col.TABLE_SCHEMA = DATABASE() AND col.TABLE_NAME = e.t AND col.COLUMN_NAME = e.c
  WHERE col.COLUMN_NAME IS NULL
  GROUP BY e.t
  UNION ALL
  SELECT '4-MOTOR_NAO_INNODB', TABLE_NAME, ENGINE FROM information_schema.TABLES
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE' AND ENGINE <> 'InnoDB'
) resultado
ORDER BY tipo, tabela;
